---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  reviews:
    title: Reviews
    output: false
    sort_by: year
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: pages
    type: pages
  values:
    lang: en
- scope:
    path: es_pages
    type: pages
  values:
    lang: es
- scope:
    path: pages/tours/driving
    type: pages
  values:
    has_tour_faq: true
- scope:
    path: pages/tours/guided
    type: pages
  values:
    has_tour_faq: true
- scope:
    path: pages/tours/walking
    type: pages
  values:
    has_tour_faq: true
- scope:
    path: es_pages/tours
    type: pages
  values:
    has_tour_faq: true
- scope:
    path: pages/test
    type: pages
  values:
    sitemap: false
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: http://www.rhodesprivatetours.com
twitter_username: jekyllrb
github_username: jekyll
i18n: true
langs:
- en
- es
default_lang: en
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-redirect-from
google_analytics: UA-1499974-1
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- dist
- gulpfile.js
- package.json
- package-lock.json
