---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Data
- type: document
  path: _data/all_tours_names.yml
  label: Tours names
  read_only: true
- type: heading
  label: Pages
- type: document
  path: index.htm
  label: Home Page
- type: directory
  path: pages/tours-pages
  label: Tours Pages
  create: all
  match: "**/*"
- type: directory
  path: pages/services
  label: Services Pages
  create: all
  match: "**/*"
- type: document
  path: pages/info/about.md
  label: About Page
- type: document
  path: pages/info/contact.md
  label: Contact Us Page
- type: document
  path: pages/info/reviews-comments-content.md
  label: Testimonials page
  read_only: false
- type: heading
  label: Tours
- type: directory
  path: pages/tours/driving
  label: Driving Tours
  create: all
  match: "**/*"
- type: directory
  path: pages/tours/guided
  label: Guided Tours
  create: all
  match: "**/*"
  templates:
  - tour
- type: directory
  path: pages/tours/walking
  label: Walking Tours
  create: all
  match: "**/*"
  templates:
  - tour
- type: heading
  label: Links
- type: directory
  path: pages/links/historical-sites
  label: Historical Sites
  create: all
  match: "**/*"
- type: directory
  path: pages/links/ancient-sites
  label: Ancient Sites
  create: all
  match: "**/*"
- type: document
  path: pages/links/juderia.md
  label: Jewish Related Sites
- type: directory
  path: pages/links/parks-natural-beauty
  label: Parks and Natural Beauty
  create: all
  match: "**/*"
- type: directory
  path: pages/links/museums-art-galleries
  label: Museums and Art Galleries
  create: all
  match: "**/*"
- type: directory
  path: pages/quick-facts
  label: Quick Facts about Rhodes
  create: all
  match: "**/*"
- type: heading
  label: Spanish Tours
- type: directory
  path: es_pages/tours
  label: Spanish Tours
  create: all
  match: "**/*"
- type: heading
  label: Spanish Pages
- type: document
  path: es_pages/info/about.md
  label: About Us - SOBRE NOSOTROS
- type: heading
  label: Spanish Links
- type: directory
  path: es_pages/links/historical-sites
  label: Historical Sites
  create: all
  match: "**/*"
  templates:
  - photo-tour
- type: directory
  path: es_pages/links/ancient-sites
  label: Ancient Sites
  create: all
  match: "**/*"
  templates:
  - photo-tour
- type: directory
  path: es_pages/links/parks-natural-beauty
  label: Parks and Natural Beauty
  create: all
  match: "**/*"
  templates:
  - photo-tour
- type: directory
  path: es_pages/links/museums-art-galleries
  label: Museums and Art Galleries
  create: all
  match: "**/*"
  templates:
  - photo-tour
- type: document
  path: es_pages/links/juderia.md
  label: La Juderia
- type: directory
  path: es_pages/quick-facts
  label: Quick Facts about Rhodes
  create: all
  match: "**/*"
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build -d _site
  publish_command: bundle exec jekyll clean && bundle exec jekyll build -d _site &&
    gulp build
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: dist
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
