---
---

---
label: Services
hide_body: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: true
  default: ''
- name: type
  label: Type
  type: text
  hidden: true
  default: ''
- name: id
  label: Id
  type: text
  hidden: true
  default: ''
- name: permalink
  label: Permalink
  type: text
  hidden: true
  default: ''
- name: has_gallery
  label: Has gallery
  type: boolean
  hidden: true
  default: ''
- name: meta
  label: Meta
  type: field_group
  fields:
  - name: title
    label: Title
    type: text
    hidden: false
    default: ''
  - name: http_desc
    label: Http desc
    type: textarea
    hidden: false
    default: ''
  - name: description
    label: Description
    type: textarea
    hidden: false
    default: ''
  - name: keywords
    label: Keywords
    type: textarea
    hidden: false
    default: ''
  - name: abstract
    label: Abstract
    type: text
    hidden: false
    default: ''
  - name: author
    label: Author
    type: text
    hidden: false
    default: ''
  - name: copyright
    label: Copyright
    type: text
    hidden: false
    default: ''
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: subtitle
  label: Subtitle
  type: text
  hidden: false
  default: ''
- name: head_photo
  label: Head photo
  type: field_group
  fields:
  - name: src
    label: Src
    type: text
    hidden: false
    default: ''
  - name: alt
    label: Alt
    type: text
    hidden: false
    default: ''
  hidden: true
  default: ''
- name: sections
  label: Sections
  type: field_group_list
  fields:
  - name: title
    label: Title
    type: text
    hidden: false
    default: ''
  - name: subtitle
    label: Subtitle
    type: text
    hidden: false
    default: ''
  - name: text
    label: Text
    type: textarea
    hidden: false
    default: ''
    config:
      wysiwyg: true
      schema:
        format: markdown
  hidden: false
  default: ''
- name: end_page
  label: End page
  type: field_group
  fields:
  - name: long_text
    label: Long text
    type: textarea
    hidden: false
    default: ''
    config:
      wysiwyg: true
      schema:
        format: markdown
  - name: short_text
    label: Short text
    type: text
    hidden: false
    default: ''
  hidden: false
  default: ''
- name: links
  label: Links
  type: list
  hidden: true
  default: ''
pages:
- pages/services/car_driver.md
- pages/services/special_occasions.md
- pages/services/vip.md
